### ISSUE TITLE
Correct firebaseapp links on eventbrite to valleydevfest.com once we are back on Firebase

### ISSUE THREAD

**Issue by MrCsabaToth** [ValleyDevFest2016/valleydevfest#22]
Without the right URL (valleydevfest.com) neither the maps API nor the service worker is happy

**Comment by MrCsabaToth** [comment]
I still see the https://valleydevfest-620d6.firebaseapp.com/ reference on the eventbrite main site with the schedule link (https://valleydevfest-620d6.firebaseapp.com/schedule/day1) and the experts link (https://valleydevfest-620d6.firebaseapp.com/speakers/). It needs to be corrected to https://valleydevfest based links so the service worker will be happy. Do I have account for eventbrite?

**Comment by riowaller** [comment]
Sorry I didn't see this before now, but I just fixed it!

**Comment by MrCsabaToth** [comment]
Thanks! One more thing: the experts link does not seem to be fixed yet.

**Comment by riowaller** [comment]
Done!
