### ISSUE TITLE
Update Morning KeyNote

### ISSUE THREAD

**Issue by riowaller** [ValleyDevFest2016/valleydevfest#29]
8:50 - 8:55 - Irma and Rebecca- 59doc
8:55 - 9:00 - Martin - Google
9:00 - 9:05 - Dr. Carole Goldsmith  - President Fresno City College
9:05 - 9-10 - Rio - Fresno City College and GDG Fresno

**Comment by MrCsabaToth** [comment]
This will be detailed in the description of the Opening, since detailing it on the session would bloat up the beginning too much
