### ISSUE TITLE
Color Coding Tracks with Room Assignments

### ISSUE THREAD

**Issue by riowaller** [ValleyDevFest2016/valleydevfest#31]
AMP PWA track -        #ff9800 GeekWise Classroom 1
PWA track -                #00b4aa GeekWise Classroom 2
Android Track -          #78c257 GeekWise Classroom 3
Cloud Track -             #0d47a1 GeeekWise Classroom 4
Firebase Code Lab -  #311b92 Geek Wise Classroom 5 
                                    (BTW this room is not available from noon to 2pm)
Maker Space -            #7b1fa2 Geek Wise Classroom 6

**Comment by MrCsabaToth** [comment]
I assume this is fixed, changes may happen

**Comment by riowaller** [comment]
Thanks Csaba! I don't see the classroom assignment, but I see the color coded tracks! :)

**Comment by MrCsabaToth** [comment]
Reopening because of room assignments

**Comment by MrCsabaToth** [comment]
Added

**Comment by MrCsabaToth** [comment]
Reopen it Rio if it needs improvement
