### ISSUE TITLE
Title Change of Code Lab 

### ISSUE THREAD

**Issue by riowaller** [ValleyDevFest2016/valleydevfest#32]
Existing Title - Firebase code labs facilitated by Free Code Camp advocates
New Title - Interactive Google Maps code labs facilitated by Free Code Camp advocates

**Comment by MrCsabaToth** [comment]
Hold on for a second... so it won't be Firebase? We need to change the track name then

**Comment by MrCsabaToth** [comment]
Fixed, too, not deployed yet though
